export const assets = {
  achintya_logo: "/assets/achintya_logo.png",
  bedroom: "/assets/bedroom.png",
  certificate1: "/assets/certificate1.png",
  dummy_video: "/assets/dummy_video.mp4",
  flooring: "/assets/flooring.png",
  hero: "/assets/hero.png",
  kitchen: "/assets/kitchen.png",
  logo: "/assets/logo.jpeg",
  commercial: "/assets/commercial.jpg",
  residential: "/assets/residential.jpg",
  industrial: "/assets/industrial.jpg",
  amazon: "/assets/amazon.png",
  office_team: "/assets/office_team.png",
};
